#!/usr/bin/env python3
r"""
Differential fuzzer for the C regex engine (native/regex.c) against Python's
`re` as the oracle.

Method (adapted from tiny-regex-c's exrex+re harness): for each pattern, we
compare the C engine's boolean verdict to `re.search(pattern, text, re.ASCII)`
over a batch of texts — some generated by `exrex` to actually exercise the
match, some random/adversarial to exercise non-matches. Any disagreement is a
bug in the C engine (or a documented semantic divergence).

Why the oracle is sound for us:
  - We only care about the boolean "matches somewhere?" verdict, and
    re.search is unanchored — leftmost/greedy-vs-longest only affect WHERE a
    match is, never WHETHER one exists, so the verdict is unambiguous.
  - re.ASCII makes \d \w \s ASCII-only, matching our byte-level classes.
  - Python's default `.` excludes newline, matching ours.

Usage:
    scripts/regex_diff.py [--bin PATH] [--rounds N] [--seed S]

Requires: python3, and `exrex` (pip install exrex) for match generation. If
exrex is missing we fall back to random-text-only testing (weaker but still
catches divergences).
"""
import argparse
import random
import re
import subprocess
import sys

try:
    import exrex
    HAVE_EXREX = True
except ImportError:
    HAVE_EXREX = False

# Patterns valid in BOTH our engine and Python's re (no backrefs/lookaround,
# no stacked quantifiers). Curated to hit every v1 feature.
CURATED = [
    r"abc", r"^abc", r"abc$", r"^abc$", r"a.c", r".*", r"a.*z",
    r"[abc]", r"[^abc]", r"[a-f]", r"[a-fA-F0-9]", r"[]a]", r"[a-]",
    r"\d", r"\d+", r"\w+", r"\s", r"\D", r"\W", r"\S",
    r"a|b", r"a|b|c", r"(ab)+", r"(a|b)*c", r"(foo|bar)baz",
    r"a*", r"a+", r"a?", r"colou?r", r"a{2}", r"a{2,3}", r"a{2,}", r"a{0,3}",
    r"\.", r"\*", r"a\+b", r"\(x\)",
    r"Insight_[A-Za-z0-9]+_2026", r"^[A-Z][a-z]+", r"[0-9]{4}-[0-9]{2}",
    r"foo.*bar", r"^(a|b|c)+$", r"x[yz]*w",
]

ALPHABET = "abcAB012 _-.|()[]{}*+?^$\\\t\n\xc3\xa9"

def random_text(rng, maxlen=12):
    return "".join(rng.choice(ALPHABET) for _ in range(rng.randint(0, maxlen)))

def c_verdict(binpath, pattern, text):
    """Return True/False (match) or None on compile error (exit 2)."""
    p = subprocess.run([binpath, pattern], input=text.encode("utf-8", "surrogatepass"),
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if p.returncode == 0: return True
    if p.returncode == 1: return False
    return None  # compile error / crash

def py_verdict(pattern, text):
    """Return True/False, or None if Python can't compile it."""
    try:
        return re.search(pattern, text, re.ASCII) is not None
    except re.error:
        return None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bin", default="/tmp/mf_test_regex_cli")
    ap.add_argument("--rounds", type=int, default=200, help="random patterns to add")
    ap.add_argument("--texts", type=int, default=40, help="texts per pattern")
    ap.add_argument("--seed", type=int, default=1234)
    args = ap.parse_args()
    rng = random.Random(args.seed)

    if not HAVE_EXREX:
        print("[warn] exrex not installed — random-text only (pip install exrex for match generation)")

    patterns = list(CURATED)
    # random patterns built from curated fragments (both engines must accept)
    frags = [r"a", r"b", r"[0-9]", r"[a-z]", r"\d", r"\w", r".", r"(a|b)",
             r"x*", r"y+", r"z?", r"foo", r"\.", r"^", r"$"]
    for _ in range(args.rounds):
        patterns.append("".join(rng.choice(frags) for _ in range(rng.randint(1, 5))))

    total = mism = skipped = cerr = 0
    fails = []
    for pat in patterns:
        pv_compiles = py_verdict(pat, "") is not None
        texts = []
        if HAVE_EXREX and pv_compiles:
            try:
                for _ in range(3):
                    texts.append(exrex.getone(pat, limit=6))
            except Exception:
                pass
        texts += [random_text(rng) for _ in range(args.texts)]

        for t in texts:
            pv = py_verdict(pat, t)
            cv = c_verdict(args.bin, pat, t)
            if pv is None or cv is None:
                # one side rejected the pattern; only a divergence if the OTHER accepted it
                if (pv is None) != (cv is None):
                    cerr += 1
                    if len(fails) < 25:
                        fails.append(("compile-divergence", pat, t, f"py={pv} c={cv}"))
                else:
                    skipped += 1
                continue
            total += 1
            if pv != cv:
                mism += 1
                if len(fails) < 25:
                    fails.append(("verdict", pat, t, f"py={pv} c={cv}"))

    for kind, pat, t, note in fails:
        print(f"  MISMATCH [{kind}] /{pat}/ vs {t!r}: {note}")
    print(f"\ncompared={total} mismatches={mism} compile-divergences={cerr} skipped={skipped}")
    return 1 if (mism or cerr) else 0

if __name__ == "__main__":
    sys.exit(main())
